### ISSUE TITLE
on your google maps search code

### ISSUE THREAD

**Issue by pvenan** [mjrulesamrat/google_maps#1]
Hello Jay,
I have found your example for embedding google maps search on a web page really fantastic. I was just looking for something similar and have stopped searchin whe I saw your code. Thank you very very much!
I am writing to you here because I have encountered a little problem. I have been using your example on a local virtual server and it works fine but when I launch the same page on line o a remote web server it does not work. Do you have already found this and have any hints for me on founding out why?
I am trying to work it out myself but still have not found a reason why. Is there any thing to do with api keys that do not work when the call comes from a web server? I have not changed a bit in your code but it doesn't work on-line while it works perfectly locally.
I thank you in advance for any even if little help.
Pietro

**Comment by mjrulesamrat** [comment]
Hello Pietro,

Thank you very much for your appreciations.

This code sample is tested on live application. If it is not working then you should check your API keys.
If still facing problem then paste the error here. I'll try my best to help you move forward.

Best Regards,
Jay Modi

**Comment by pvenan** [comment]
Hello Jay,
Thank you very much for replying my request. In the meantime I had done
what I now see you have suggested here in your answer and solved the
problem.
It works fine now. It really only was a matter of the API key ad its
options.
Thank you very much indeed!
Pietro

2017-05-09 12:54 GMT+02:00 Jay Modi <notifications@github.com>:

**Comment by mjrulesamrat** [comment]
cool
